# Generated by Django 2.0.3 on 2020-01-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salad_type', models.CharField(choices=[('Ga', 'Garden'), ('Gr', 'Greek'), ('A', 'Antipasto'), ('T', 'Tuna')], max_length=2)),
            ],
        ),
    ]
