# Generated by Django 2.0.3 on 2020-01-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta_type', models.CharField(choices=[('Mo', 'Mozzarella'), ('Me', 'Meatballs'), ('C', 'Chicken')], max_length=2)),
            ],
        ),
    ]
