# Generated by Django 2.0.3 on 2020-01-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_dinnerplatter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(choices=[('Ch', 'Cheese'), ('I', 'Italian'), ('HC', 'Ham & Cheese'), ('Me', 'Meatball'), ('Tn', 'Tuna'), ('Tk', 'Turkey'), ('CP', 'Chicken Parmigiana'), ('EP', 'Eggplant Parmigiana'), ('St', 'Steak'), ('SC', 'Steak & Cheese')], max_length=2)),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1)),
                ('mushrooms', models.BooleanField()),
                ('green_peppers', models.BooleanField()),
                ('onions', models.BooleanField()),
                ('extra_cheese', models.BooleanField()),
            ],
        ),
    ]
