# Generated by Django 2.0.3 on 2020-01-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_sub1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(choices=[('SPO', 'Sausage, Peppers & Onions'), ('H', 'Hamburger'), ('C', 'Cheeseburger'), ('FC', 'Fried Chicken'), ('V', 'Veggie')], max_length=3)),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=1)),
                ('extra_cheese', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='dinnerplatter',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='sub1',
            name='extra_cheese',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sub1',
            name='green_peppers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sub1',
            name='mushrooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sub1',
            name='onions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sub1',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=1),
        ),
    ]
