# Generated by Django 2.0.3 on 2020-01-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200112_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(choices=[('R', 'Regular'), ('Si', 'Sicilian')], max_length=2)),
                ('pizza_top', models.CharField(default='', max_length=6)),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=1)),
            ],
        ),
    ]
